name: Feature Pipeline

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Read package.json version
        run: |
          APP_VERSION=$(jq -r .version package.json)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Check Version
        run: echo "$APP_VERSION"

      - name: Install Dependencies
        run:  npm ci --ignore-scripts

      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Sonar Quality Gate check
        id: sonar_check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io


      - name: Slack Alert
        if: always()
        uses: slackapi/slack-github-action@v3.0.3
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "✅ NodeJS Feature Pipeline Success"

              

